prefix-dev/rip

- .pre-commit-config.yaml
> feat: add pre-commit config

- crates/rattler_installs_packages/src/package_database.rs
When `rip` tries to retrieve metadata for a version it can now use multiple artifacts to get the metadata from in the case that it cannot parse one of the metadata entries.
This should be fine because the metadata for a version should be the same.
Improves this issue: https://github.com/prefix-dev/rip/issues/27
> Skips artifacts that have incorrect metadata

- Cargo.lock
- crates/rattler_installs_packages/Cargo.toml
- crates/rattler_installs_packages/src/env_markers.rs
- crates/rip_bin/src/main.rs
> run which to find python executable

- CONTRIBUTING.md
- Cargo.toml
- README.md
> fix: CONTRIBUTING, Cargo.toml and README.md

- crates/rattler_installs_packages/src/lib.rs
- crates/rattler_installs_packages/src/record.rs
- crates/rattler_installs_packages/src/uninstall.rs
Add the ability to remove a python package.
> feat: uninstall a python distribution from an environment

- crates/rattler_installs_packages/src/artifact.rs
- crates/rattler_installs_packages/src/distribution_finder.rs
- crates/rattler_installs_packages/src/env_markers.rs
- crates/rattler_installs_packages/src/tags/from_env.rs
- crates/rattler_installs_packages/src/uninstall.rs
- crates/rattler_installs_packages/src/utils.rs
Changes python detection when using homebrew.
> feat: change in python detection

- crates/rip_bin/src/main.rs
> feat: changed env marker logging to debug

- Cargo.lock
- Cargo.toml
- crates/rattler_installs_packages/Cargo.toml
- crates/rattler_installs_packages/src/sdist.rs
This is needed so that we can set-up a build environment to build the sdist.
> Read build-info from toml

- crates/rattler_installs_packages/src/artifact_name.rs
- crates/rattler_installs_packages/src/tags/from_env.rs
Fix if a package name has multiple dashes.
> feat: fix if a package name has multiple dashes

- crates/rattler_installs_packages/src/distribution_finder.rs
- crates/rattler_installs_packages/src/env_markers.rs
- crates/rattler_installs_packages/src/lib.rs
- crates/rattler_installs_packages/src/system_python.rs
- crates/rattler_installs_packages/src/tags/from_env.rs
- crates/rattler_installs_packages/src/utils.rs
- crates/rattler_installs_packages/src/wheel.rs
Allows the getting of the system python intepreter version. 
Also, refactors the code a bit so that we have a seperate file for this stuff.
> feat: get the system python interpreter version

- crates/rattler_installs_packages/src/sdist.rs
- crates/rattler_installs_packages/src/snapshots/rattler_installs_packages__sdist__tests__build_rich_no_metadata.snap
- crates/rattler_installs_packages/src/snapshots/rattler_installs_packages__sdist__tests__build_rich_with_metadata.snap
- crates/rattler_installs_packages/src/snapshots/rattler_installs_packages__sdist__tests__sdist_metadata.snap
- crates/rattler_installs_packages/src/wheel.rs
- crates/rattler_installs_packages/src/wheel_builder_frontend.py
Fixes actual building of wheels. Small missassumption in python script.
> fix: fixes actual wheel building

- crates/rattler_installs_packages/src/wheel_builder.rs
- crates/rattler_installs_packages/src/wheel_builder_frontend.py
@tdejager I also made a few adjustments :)
> use file to communicate from wheel build function

- crates/rattler_installs_packages/src/wheel_builder/build_environment.rs
- crates/rattler_installs_packages/src/wheel_builder/mod.rs
Small refactor to move build env file.
> refactor: move build env

- crates/rattler_installs_packages/src/python_env/byte_code_compiler.rs
Add better handling of when the bytecode compiler stopped prematurely.
> fix: more reliable byte code compiler

- README.md
- crates/rip_bin/src/main.rs
Adds installation options in the binary, so that we can test building and installation.
Closes #64
> feat: installation into binary

- Cargo.lock
- crates/rattler_installs_packages/src/artifacts/sdist.rs
- crates/rattler_installs_packages/src/python_env/venv.rs
- crates/rattler_installs_packages/src/resolve/dependency_provider.rs
- crates/rattler_installs_packages/src/resolve/solve.rs
- crates/rattler_installs_packages/src/wheel_builder/build_environment.rs
- crates/rattler_installs_packages/src/wheel_builder/mod.rs
- crates/rip_bin/src/main.rs
Moves the `PythonLocation` to the resolve options, I think it makes more sense there 👍
> feat: switch the interpreter to the build options

- crates/rattler_installs_packages/src/wheel_builder/build_environment.rs
Because the scripts directory was not available on the path some build systems like `maturin` that depend on a binary in the script folder fail.
Fixes #137, now maturin (the executable) can be found when executing the python maturin build backend.
> Modify the PATH when running metadata build or actual build for wheels

- Cargo.lock
- crates/rattler_installs_packages/Cargo.toml
- crates/rattler_installs_packages/src/artifacts/sdist.rs
- crates/rattler_installs_packages/src/artifacts/wheel.rs
- crates/rattler_installs_packages/src/index/file_store.rs
- crates/rattler_installs_packages/src/python_env/distribution_finder.rs
- crates/rattler_installs_packages/src/python_env/uninstall.rs
- crates/rattler_installs_packages/src/python_env/venv.rs
- crates/rattler_installs_packages/src/types/record.rs
- crates/rattler_installs_packages/src/wheel_builder/build_environment.rs
- crates/rattler_installs_packages/src/wheel_builder/mod.rs
- crates/rattler_installs_packages/src/wheel_builder/wheel_cache.rs
Seemed pretty useful during testing.
> Use fs_err instead of std::fs for better error messages

- crates/rattler_installs_packages/src/types/core_metadata.rs
> misc: changes logging level of a Requires-Dist cant be parsed

- Cargo.lock
- crates/rattler_installs_packages/Cargo.toml
- crates/rattler_installs_packages/src/artifacts/sdist.rs
- crates/rattler_installs_packages/src/index/http.rs
- crates/rattler_installs_packages/src/index/package_database.rs
- crates/rattler_installs_packages/src/wheel_builder/mod.rs
- crates/rip_bin/Cargo.toml
- crates/rip_bin/src/main.rs
Follow-up of change in rattler_networking
> Move PackageDb to ClientWithMiddleware

- crates/rattler_installs_packages/src/wheel_builder/wheel_cache.rs
Adds a small API to list the wheels that have been found in the cache by name.
> Expose the API to list locally built wheels

- crates/rattler_installs_packages/src/index/package_database.rs
- crates/rattler_installs_packages/src/resolve/dependency_provider.rs
- crates/rip_bin/src/main.rs
> fix: fixes locked packages being passed in from pixi and using WheelTags from correct interpreter

- Cargo.lock
- crates/rattler_installs_packages/src/wheel_builder/error.rs
- crates/rattler_installs_packages/src/wheel_builder/mod.rs
I feel it was cluttering up the file a bit :)
> refactor: move wheel_builder error type as it was growing large

- crates/rattler_installs_packages/src/artifacts/mod.rs
- crates/rattler_installs_packages/src/artifacts/sdist.rs
- crates/rattler_installs_packages/src/artifacts/stree.rs
- crates/rattler_installs_packages/src/artifacts/wheel.rs
- crates/rattler_installs_packages/src/index/direct_url/file.rs
- crates/rattler_installs_packages/src/index/direct_url/http.rs
- crates/rattler_installs_packages/src/index/package_database.rs
- crates/rattler_installs_packages/src/types/artifact.rs
- crates/rattler_installs_packages/src/types/artifact_name.rs
- crates/rattler_installs_packages/src/types/mod.rs
- crates/rattler_installs_packages/src/types/project_info.rs
Introduced `HasArtifactName` so that we can also use `is` on the `STree` type. In addition I moved some things to their own files :)
> feat: introduced `HasArtifactName` trait

- crates/rattler_installs_packages/src/artifacts/sdist.rs
- crates/rattler_installs_packages/src/artifacts/snapshots/rattler_installs_packages__artifacts__sdist__tests__get_only_metadata_for_local_stree_rich_without_calling_available_artifacts.snap
- crates/rattler_installs_packages/src/index/direct_url/file.rs
- crates/rattler_installs_packages/src/index/direct_url/git.rs
- crates/rattler_installs_packages/src/index/direct_url/http.rs
- crates/rattler_installs_packages/src/index/direct_url/mod.rs
- crates/rattler_installs_packages/src/index/package_database.rs
refactor a little get_metadata so it's support returning metadata for stree also
> feat: add support for stree in get_metadata

- .github/workflows/rust-compile.yml
- Cargo.lock
- README.md
- crates/rattler_installs_packages/src/resolve/solve_options.rs
- crates/rip_bin/Cargo.toml
- crates/rip_bin/src/cli/mod.rs
- crates/rip_bin/src/cli/resolve.rs
- crates/rip_bin/src/cli/wheels.rs
- crates/rip_bin/src/lib.rs
- crates/rip_bin/src/main.rs
- end_to_end_tests/test_endtoend.py
This adds a more flexible way to add commands to the binary. I want to update the GIF once this lands so that you do not see the ugly branch name in the gif.
> refactor: changed the CLI to have different subcommands e.g `resolve` and `install`

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
A release to update dependencies! And we had some non-released fixes, too.
> release 0.9.0
