Cargo.lock, crates/index/Cargo.toml, crates/rattler_installs_packages/Cargo.toml, crates/rip_bin/Cargo.toml
There was a warning regarding a transient `atty` dependency.
=> update all dependencies to get rid of dependabot warning 

crates/rattler_installs_packages/src/package_database.rs
Don't cache the http as we also cache it in the file db.
=> feat: don't cache metadata cause we are storing it already

crates/rattler_installs_packages/src/core_metadata.rs
This ignores invalidly formatted requirements when parsing metadata. The same thing [happens in pip](https://github.com/pypa/pip/blob/2ba5acc8a4772ca1dc0d62a2dfe8967af28649d6/src/pip/_internal/resolution/resolvelib/factory.py#L392).
Fix #27
=> fix: ignore invalid requirements

Cargo.lock, crates/rattler_installs_packages/Cargo.toml, crates/rattler_installs_packages/src/env_markers.rs, crates/rattler_installs_packages/src/html.rs, crates/rattler_installs_packages/src/lib.rs, crates/rattler_installs_packages/src/pep508.py, crates/rattler_installs_packages/src/requirement.rs, crates/rattler_installs_packages/src/resolve.rs, crates/rip_bin/src/main.rs
Adds support for detecting and evaluating environment markers. Environment markers can be extracted from a python executable by running a simple python script.  
Fixes #34 as the proper python markers are now parsed and evaluated:
```
>rip  "scipy>=1.4.0"
2023-10-02T13:34:12.758759Z  INFO rip: extracted the following environment markers from the system python interpreter:
Pep508EnvMakers {
os_name: "nt",
sys_platform: "win32",
platform_machine: "AMD64",
platform_python_implementation: "CPython",
platform_release: "10",
platform_system: "Windows",
platform_version: "10.0.22621",
python_version: "3.8",
python_full_version: "3.8.17",
implementation_name: "cpython",
implementation_version: "3.8.17",
}
2023-10-02T13:34:12.759610Z  INFO rattler_installs_packages::resolve: collecting scipy …
```
=> feat: env markers

crates/rattler_installs_packages/src/requirement.rs, crates/rattler_installs_packages/src/resolve.rs, crates/rattler_installs_packages/src/specifier.rs
Sometimes metadata contains specifiers like `>=3.5.*`. This is ambiguous because it either means `3.5.*` or `>=3.5`. The former is more restrictive than the latter but most likely one means the latter. This PR adds a boolean that allows a user to specify whether this should result in an error or whether the least restrictive bound should be chosen. With this PR the resolver chooses the least restrictive bound.
Fix #38
=> fix: allow wildcards in ambiguos specifiers

.pre-commit-config.yaml, Cargo.lock, crates/rattler_installs_packages/Cargo.toml, crates/rattler_installs_packages/src/artifact_name.rs, crates/rattler_installs_packages/src/lib.rs, crates/rattler_installs_packages/src/resolve.rs, crates/rattler_installs_packages/src/tags/from_env.rs, crates/rattler_installs_packages/src/tags/mod.rs, crates/rattler_installs_packages/src/tags/platform_tags.py, crates/rattler_installs_packages/src/utils.rs, crates/rattler_installs_packages/vendor/packaging/LICENSE, crates/rattler_installs_packages/vendor/packaging/LICENSE.APACHE, crates/rattler_installs_packages/vendor/packaging/LICENSE.BSD, crates/rattler_installs_packages/vendor/packaging/__init__.py, crates/rattler_installs_packages/vendor/packaging/_elffile.py, crates/rattler_installs_packages/vendor/packaging/_manylinux.py, crates/rattler_installs_packages/vendor/packaging/_musllinux.py, crates/rattler_installs_packages/vendor/packaging/_parser.py, crates/rattler_installs_packages/vendor/packaging/_structures.py, crates/rattler_installs_packages/vendor/packaging/_tokenizer.py, crates/rattler_installs_packages/vendor/packaging/markers.py, crates/rattler_installs_packages/vendor/packaging/metadata.py, crates/rattler_installs_packages/vendor/packaging/requirements.py, crates/rattler_installs_packages/vendor/packaging/specifiers.py, crates/rattler_installs_packages/vendor/packaging/tags.py, crates/rattler_installs_packages/vendor/packaging/utils.py, crates/rattler_installs_packages/vendor/packaging/version.py, crates/rip_bin/src/main.rs
Adds support to extract packaging tags from the Python interpreter and use that information in the solver. This information can also be used to determine the most compatible wheel, but although its implemented it is not yet used in this PR.
The compatible tags are also outputted on running. Note that this could impact the resolve result because some wheels might not be compatible with your Python interpreter.
The compatible tags are extracted using the wonderful `packaging` library. The library is vendored and bundled with the executable to ensure that you still only need Python to run the rip binary.
Compatible tags are an optional argument for the resolver. If you don't care you can just pass `None` in which case the artifacts are not filtered based on the tag compatibility.
Related to …
=> feat: extract and check wheel tags

crates/rattler_installs_packages/src/artifact.rs, crates/rattler_installs_packages/src/distribution_finder.rs, crates/rattler_installs_packages/src/lib.rs, test-data/find_distributions/Lib/site-packages/zipp-3.17.0.dist-info/.gitkeep, test-data/find_distributions/Lib/site-packages/zipp/.gitkeep
- Renames (and exposes) `InstallOptions` to `UnpackWheelOptions`.
- Fixes a bug where empty directories would be discovered as distributions.
=> fix: expose InstallOptions renamed as UnpackWheelOptions

crates/rattler_installs_packages/Cargo.toml, crates/rattler_installs_packages/src/distribution_finder.rs, crates/rattler_installs_packages/src/tags/mod.rs
Small refactor to use the `WheelTag` type in installed distributions.
=> refactor: use WheelTag in Distribution

Cargo.lock, crates/rattler_installs_packages/Cargo.toml, crates/rattler_installs_packages/src/resolve.rs
This allows indicating that some versions are excluded for reasons outside of the solver. These reasons are included in the error message which should make it more clear to the user why a solution could not be found. For instance, this is especially useful if a package is only available as an sdist.
For example when trying to resolve `sdist`.
before (`main`)
```
$ cargo run -- sdist
...
× Could not solve for the requested requirements:
│ No candidates were found for sdist *.
```
after:
```
$ cargo run -- sdist
...
× Could not solve for the requested requirements:
│ The following packages are incompatible
│ |-- sdist * cannot be installed because there are no viable options:
│     |-- sdist 0.0.0 is excluded because there are no wheels available
```
=> bump: resolvo 0.2.0

.github/workflows/rust-compile.yml, crates/rattler_installs_packages/src/lib.rs, crates/rattler_installs_packages/src/resolve.rs, crates/rattler_installs_packages/tests/resolver.rs, crates/rattler_installs_packages/tests/snapshots/resolver__no_sdists.snap, crates/rip_bin/src/main.rs
This adds the option to specify whether you want to use sdists, prefer them or only use sdists.
=> feat: allow specifying whether you want sdists or not

crates/index/src/main.rs, crates/rattler_installs_packages/src/artifact.rs, crates/rattler_installs_packages/src/lib.rs, crates/rattler_installs_packages/src/package_database.rs, crates/rattler_installs_packages/src/resolve.rs, crates/rattler_installs_packages/src/sdist.rs, crates/rattler_installs_packages/src/wheel.rs
Did the following refactors:
- The metadata methods of `PackageDb` are less generic so that it is easier to distinguish between different code paths for wheels and SDists
- Removed `ArtifactMetadata` trait as we were not really using this anymore.
- Paves the way for doing building of SDist in a seperate builder and handing this to the PackageDb.
=> refactor: refactored package-db module to make it a bit less generic

crates/rattler_installs_packages/benches/html.rs, crates/rattler_installs_packages/src/artifact_name.rs, crates/rattler_installs_packages/src/html.rs, crates/rattler_installs_packages/src/lib.rs, crates/rattler_installs_packages/src/package_database.rs, crates/rattler_installs_packages/src/resolve.rs, crates/rattler_installs_packages/src/sdist.rs, crates/rattler_installs_packages/src/venv.rs, crates/rattler_installs_packages/src/wheel.rs
Now uses normalized or canonical package name to do the actual parsing.
Added some extra test to verify if this is working.
=> feat: refactored name parsing from artifacts

crates/rattler_installs_packages/src/distribution_finder.rs, crates/rattler_installs_packages/src/tags/mod.rs, test-data/find_distributions/Lib/site-packages/Werkzeug-1.0.1.dist-info/WHEEL
WHEEL files can contain compound tags like: `cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64`.
=> fix: wheel tags can contain compound tags

crates/rattler_installs_packages/src/venv.rs, crates/rattler_installs_packages/src/wheel.rs
Returns the `.dist-info` folder location after a wheel has been unpacked.
=> feat: expose dist-info folder after install

crates/rattler_installs_packages/src/uninstall.rs
Remove empty directories during the removal of distributions.
Closes #92
=> feat: remove empty folders on uninstall

crates/rattler_installs_packages/src/index/mod.rs
Fixes an issue with an ambiguous import:
```
error[E0659]: `http` is ambiguous
--> C:\Users\User\.cargo\git\checkouts\rattler_installs_packages-3677d742e8596976\7de2c7a\crates\rattler_installs_packages\src\index\mod.rs:11:9
|
11 | pub use http::CacheMode;
|         ^^^^ ambiguous name
|
= note: ambiguous because of multiple potential import sources
= note: `http` could refer to a crate passed with `--extern`
= help: use `::http` to refer to this crate unambiguously
note: `http` could also refer to the module defined here
--> C:\Users\User\.cargo\git\checkouts\rattler_installs_packages-3677d742e8596976\7de2c7a\crates\rattler_installs_packages\src\index\mod.rs:6:1
|
6  | mod http;
| ^^^^^^^^^
= help: use `self::http` to refer to this module unambiguously
```
=> fix: ambigious import

Cargo.lock, crates/rattler_installs_packages/Cargo.toml, crates/rattler_installs_packages/src/artifacts/sdist.rs, crates/rattler_installs_packages/src/index/package_database.rs, crates/rattler_installs_packages/src/wheel_builder/build_environment.rs, crates/rattler_installs_packages/src/wheel_builder/mod.rs
Adds recursion to recursively build sdists if needed. Could use a bit of a nicer design but works for now :)
=> feat: sdists can now build sdists if needed

crates/rattler_installs_packages/Cargo.toml, crates/rip_bin/Cargo.toml, crates/test-utils/Cargo.toml
This PR prepares the repository for release.
@tdejager 
Make sure you have `cargo-release` installed:
```shell
cargo install cargo-release
```
Then simply run the following from the root of the repository:
```shell
cargo release # verify that everything is as you expect it
cargo release --execute # actually publish the release
git push upstream v0.1.0 # push the tag to the upstream repository
```
=> chore: prepare release

crates/rattler_installs_packages/src/artifacts/sdist.rs, crates/rattler_installs_packages/src/python_env/mod.rs, crates/rattler_installs_packages/src/python_env/venv.rs, crates/rattler_installs_packages/src/resolve/dependency_provider.rs, crates/rattler_installs_packages/src/resolve/solve.rs, crates/rattler_installs_packages/src/wheel_builder/build_environment.rs, crates/rattler_installs_packages/src/wheel_builder/mod.rs, crates/rip_bin/src/main.rs
This makes it more explicit everywhere so that we can actually resolve environments using a custom interpreter.
=> Adds the ability to specify the python interpeter for wheel building

crates/rattler_installs_packages/src/index/file_store.rs, crates/rattler_installs_packages/src/index/http.rs, crates/rattler_installs_packages/src/index/package_database.rs
Made the file locking code async. As this cannot block the thread as the previous implementation was doing.
=> Async file locking

crates/rattler_installs_packages/Cargo.toml, crates/rattler_installs_packages/src/artifacts/wheel.rs, crates/rattler_installs_packages/src/python_env/system_python.rs, crates/rattler_installs_packages/src/python_env/venv.rs
Create python venv directly from rust.
Implementation based on built-in venv module.
I've changed a little `system_python_executable` implementation. `which` does not return original interpreter but a shim path when using pyenv. This does not work well when we later create `pyenv.cfg` and set `home =`
Closes: #83
=> feat: create venv from rust

crates/rattler_installs_packages/src/wheel_builder/mod.rs
This did not need to have the same lifetime, causes issues down the line.
=> Using too constraining lifetime for WheelBuilder

crates/rip_bin/src/main.rs
Use the python location to create the `venv` when running `--install--into`.
=> feat: use python location for venv in bin

.github/workflows/rust-compile.yml, crates/rattler_installs_packages/src/python_env/venv.rs
With this fix we will move python.exe / pythonw.exe from Lib/Scripts/nt when running on windows.
Also I've added an edge case for a situation when we are using python built from source
=> fix: add missing files for windows when creating venv

crates/rattler_installs_packages/src/python_env/mod.rs, crates/rattler_installs_packages/src/python_env/system_python.rs
Moves `PythonInterpreterVersion` and its associated error enum in to the public API.
Closes #155
=> feat: move PythonInterpreterVersion to the public API

crates/rattler_installs_packages/src/index/html.rs
The `devpi` server apparently has sdists that come with an empty string for python requirement. Not sure how widespread that is.
=> fix parsing a tag with empty python version requirement

crates/rattler_installs_packages/src/index/package_database.rs, crates/rattler_installs_packages/src/resolve/dependency_provider.rs
I we find `metadata` for an artifact it does not really matter that the others have errored out I think. But if we *cannot* find any then we want to make this into an error, because currently the thread will panic after this happens.
This should also enable pixi users to see this error.
=> misc: improve logging level of wheel build failures

crates/rattler_installs_packages/src/artifacts/wheel.rs, crates/rattler_installs_packages/src/types/direct_url_json.rs, crates/rattler_installs_packages/src/types/mod.rs
Adds the ability to write a `direct_url.json` file for unpacking. Use-case would be mainly for non-pypi dependencies like source or git.
@nichmor you can check if this is enough for your needs.
=> feat: adds ability to write `direct_url.json` file

Cargo.lock, crates/rattler_installs_packages/src/resolve/dependency_provider.rs, crates/rattler_installs_packages/src/resolve/solve.rs, crates/rip_bin/src/main.rs
Cancel on failure to extract metadata instead of backtracking, should be more similar as to how pip does it. Does not continue to backtrack when this happens.
For example, `cargo r mamba-ssm` which fails to build for me results in:
```
2024-01-26T13:02:13.118203Z ERROR rattler_installs_packages::index::package_database: Error from source distributions 'mamba_ssm-1.1.1.tar.gz' skipped:
could not build wheel: Traceback (most recent call last):
File "/var/folders/fg/9x0q93cj3ls9nktfdlc_09080000gn/T/.tmpRfHc2U/build_frontend.py", line 124, in <module>
get_requires_for_build_wheel(backend, work_dir)
File "/var/folders/fg/9x0q93cj3ls9nktfdlc_09080000gn/T/.tmpRfHc2U/build_frontend.py", line 58, in get_requires_for_build_wheel
result = f()
^^^
File …
```
=> feat: cancel on metadata failure

crates/rattler_installs_packages/src/index/package_database.rs, crates/rattler_installs_packages/src/resolve/dependency_provider.rs, crates/rattler_installs_packages/src/resolve/solve.rs
Uses `miette` to use cancellation so that we can return an actual error. It's still a bit ugly because we need to convert to using our own error types everywhere, but I wanted a fix so that I get proper error reporting in pixi CI.
=> feat: now uses miette error for the cancellation of resolvo

crates/rattler_installs_packages/Cargo.toml
Use the official release of `async_http_range_reader`
=> chore: use async_range_reader 0.6.0 over git dependency

Cargo.lock, Cargo.toml, crates/rattler_installs_packages/Cargo.toml
Removes the git dependency and just directly depend on release of resolvo.
=> bump: resolvo v0.3.0

Cargo.lock, crates/rattler_installs_packages/Cargo.toml, crates/rattler_installs_packages/src/artifacts/sdist.rs, crates/rattler_installs_packages/src/index/package_database.rs, crates/rattler_installs_packages/src/resolve/dependency_provider.rs, crates/rattler_installs_packages/src/resolve/solve.rs, crates/rattler_installs_packages/src/wheel_builder/build_environment.rs, crates/rattler_installs_packages/src/wheel_builder/mod.rs, crates/rip_bin/src/main.rs
Removes the lifetimes from `WheelBuilder` and `resolve` in favor of some `Arc`s. I assume this will have only a very minimal impact on performance/memory usage but it makes the code a hell of a lot easier to understand. 
The motivation to remove them is for concurrency where I often want to `tokio::spawn` stuff. This requires that the future is `'static` which is often not possible with all the lifetimes we used.
Most likely some lifetimes could be returned in the `resolve` function (which don't bubble through the rest of the code) but we can do that later.
Some of the things I turned into Arcs:
* `PackageDb`: we often want to share this between different tasks and datastructures.
* `WheelTags`: this can amount to a lot of data so I thought it would be worth to wrap in an Arc.
* …
=> refactor: remove all lifetimes

crates/rattler_installs_packages/src/artifacts/sdist.rs, crates/rattler_installs_packages/src/artifacts/snapshots/rattler_installs_packages__artifacts__sdist__tests__build_rich_git_reference_source_code.snap, crates/rattler_installs_packages/src/index/package_database.rs, crates/rattler_installs_packages/src/resolve/dependency_provider.rs, crates/rattler_installs_packages/src/resolve/solve.rs, crates/rattler_installs_packages/src/types/artifact_name.rs
This PR reverts the changes previous made for PinnedPackage
and will store 
`version: pep440_version`
and an `url: Optional<Url>` in case when pinnedpackage was provided by direct url
=> fix: use version and url in pinned package

crates/rattler_installs_packages/src/artifacts/sdist.rs, crates/rattler_installs_packages/src/artifacts/wheel.rs, crates/rattler_installs_packages/src/index/direct_url/file.rs, crates/rattler_installs_packages/src/index/direct_url/git.rs, crates/rattler_installs_packages/src/index/direct_url/http.rs, crates/rattler_installs_packages/src/index/direct_url/mod.rs, crates/rattler_installs_packages/src/index/git_interop.rs, crates/rattler_installs_packages/src/index/mod.rs, crates/rattler_installs_packages/src/index/package_database.rs, crates/rattler_installs_packages/src/python_env/byte_code_compiler.rs, crates/rattler_installs_packages/src/resolve/dependency_provider.rs, crates/rattler_installs_packages/src/types/artifact_name.rs
This clears up the code a bit and makes it easier to implement actual Artifact support for STree and other `direct_url` dependencies.
=> refactor: refactored some logic out of the `PackageDb`

Cargo.lock, crates/rattler_installs_packages/Cargo.toml
Bumps `pep440_rs` and `pep508_rs` to latest. Maybe we should reexport the types from these crates since `Version`, and friends are used a lot throughout this crate.
=> bump: pep440 and pep508

crates/rattler_installs_packages/src/python_env/distribution_finder.rs, crates/rattler_installs_packages/src/python_env/mod.rs
Adds `find_distributions_in_directory` which allows searching for Python distributions in an arbitrary directory instead of a venv. This allows checking if a directory contains a distributions without having to reason about venvs.
=> feat: find distributions in arbitrary directory

crates/rattler_installs_packages/src/artifacts/mod.rs, crates/rattler_installs_packages/src/artifacts/sdist.rs, crates/rattler_installs_packages/src/artifacts/stree.rs, crates/rattler_installs_packages/src/artifacts/wheel.rs, crates/rattler_installs_packages/src/index/direct_url/file.rs, crates/rattler_installs_packages/src/index/direct_url/http.rs, crates/rattler_installs_packages/src/index/package_database.rs, crates/rattler_installs_packages/src/resolve/dependency_provider.rs, crates/rattler_installs_packages/src/types/artifact.rs, crates/rattler_installs_packages/src/types/mod.rs, crates/rattler_installs_packages/src/wheel_builder/build_environment.rs, crates/rattler_installs_packages/src/wheel_builder/mod.rs, crates/rattler_installs_packages/src/wheel_builder/wheel_cache.rs
Renamed trait to:
* `ArtifactFromBytes` represent an artifact that can be constructed from bytes
* `ArtifactFromSource` represents an artifiact that can be built from source.
Also moved the traits together.
=> refactor: renamed artifact traits, so that it is more clear what the use of each is

crates/rattler_installs_packages/src/utils/streaming_or_local.rs
Fixes a bug when pulling sdists where data from a previous chunk will be written to the end of the final chunk, causing gzip to throw errors.
=> fix: only write out amount of bytes read

crates/rattler_installs_packages/src/index/http.rs, crates/rattler_installs_packages/src/resolve/dependency_provider.rs
Otherwise, `apache-airflow[all]` would just start failing randomly. Because of too many open files and other dns errors. This fixes that problem. I don't know if 30 is a good default but seems to work for me 👼
=> fix: limits the amount of concurrent tasks with the new async resolvo code

crates/rattler_installs_packages/src/wheel_builder/build_environment.rs
Print the potential error from PackageDB during a wheel build.
=> fix: print packagedb error during wheel build

crates/rattler_installs_packages/src/artifacts/sdist.rs, crates/rattler_installs_packages/src/wheel_builder/mod.rs
This should get around the tomli issue.
Astral's uv faced the same issue and this is the fix they are using.
=> fix: don't preservere mtime when unpacking tar archive

Cargo.lock, crates/rattler_installs_packages/Cargo.toml, crates/rattler_installs_packages/src/python_env/system_python.rs
On windows, when python was installed using `pixi`, rip was not able to find the python executable because the extension was `.bat`. This PR reintroduces `which` to find the initial python binary to invoke, following by the existing code to determine python binary using python itself.
=> refactor: use which to find the correct python executable

crates/rattler_installs_packages/src/index/mod.rs, crates/rattler_installs_packages/src/index/package_database.rs, crates/rattler_installs_packages/src/utils/test.rs, crates/rattler_installs_packages/src/wheel_builder/mod.rs, crates/rip_bin/src/main.rs
Adds an option to the `PackageDb` to trust the server age for requests regarding `available_artifacts`. This saves us from doing a bunch of requests. Also adds `--use-server-timout` to binary for testing this.
=> feat: adds the ability to use the server age while requesting available artifacts

crates/rattler_installs_packages/src/index/package_database.rs
Getting the URL from the response extensions instead of simply using the input URL strips authentication data from the URL.  Doing this not only prevents downloading artifacts from a private registry using basic auth, but also causes caching errors when removing a given lock because of the way cache keys are calculated.
=> fix: don't strip auth from url
